### ISSUE TITLE
Try to run uwsgi with pyparallel with threaded workers

### ISSUE THREAD

**Issue by thedrow** [pyparallel/pyparallel#3]
I'm wondering what it will take to make that happen.
Is it a none effort plug and play?
Has anyone tried yet?

**Comment by auvipy** [comment]
@thedrow from the last issue, first the library need to be synced with 3.5/3.6, then have to implement posix/linux part which need a lot of time. https://github.com/pyparallel/pyparallel/issues/2#issuecomment-145073809

**Comment by thedrow** [comment]
uWSGI supports windows so it might be possible to try.

**Comment by auvipy** [comment]
owhh!! I didn't know it!

**Comment by auvipy** [comment]
ever tried?

**Comment by thedrow** [comment]
Nah. Seems like this won't be in mainline anyway.
