### ISSUE TITLE
Async has no server issue.

### ISSUE THREAD

**Issue by niravtadvaiya** [pyparallel/pyparallel#5]
Hello There,
I'm trying to execute given example. I'm getting error : server = async.server('0.0.0.0', 8080)
AttributeError: module 'async' has no attribute 'server'

Thank you in Advance

**Comment by tpn** [comment]
Hi, the async module got renamed to 'parallel', in order to not conflict with the new async keyword in Python.

So try:

```
server = parallel.server('0.0.0.0', 8080)
```

**Comment by niravtadvaiya** [comment]
Please update the example.

**Comment by niravtadvaiya** [comment]
Thank you for the quick response.

**Comment by tpn** [comment]
I've just updated the examples in README.md.  Thanks!
